Remedy `make format && make lint` warnings
poetry run flake8 --ignore=W503,E501,F401 sherpa_ai tests

sherpa_ai/utils.py:497:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`

sherpa_ai/utils.py:507:13: F841 local variable 'e' is assigned to but never used

sherpa_ai/utils.py:554:114: W291 trailing whitespace

tests/integration_tests/test_entity_citation_validator.py:53:5: F811 redefinition of unused 'get_llm' from line 13

tests/integration_tests/test_qa_agent_actions.py:46:49: F811 redefinition of unused 'get_llm' from line 8

tests/integration_tests/test_qa_agent_actions.py:72:55: F811 redefinition of unused 'get_llm' from line 8

tests/unit_tests/test_util.py:244:1: F811 redefinition of unused 'test_extract_numbers_from_text' from line 182

tests/unit_tests/test_util.py:299:1: F811 redefinition of unused 'test_extract_numbers_from_text' from line 244

tests/unit_tests/test_util.py:382:25: E712 comparison to True should be 'if cond is True:' or 'if cond:'

tests/unit_tests/test_util.py:390:25: E712 comparison to False should be 'if cond is False:' or 'if not cond:'

tests/unit_tests/test_util.py:405:1: F811 redefinition of unused 'test_text_similarity_with_entities_exist' from line 397