Remedy `make format && make lint` warnings
poetry run flake8 --ignore=W503,E501,F401 sherpa_ai tests
sherpa_ai/utils.py:497:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
sherpa_ai/utils.py:507:13: F841 local variable 'e' is assigned to but never used
sherpa_ai/utils.py:554:114: W291 trailing whitespace
tests/integration_tests/test_entity_citation_validator.py:53:5: F811 redefinition of unused 'get_llm' from line 13
tests/integration_tests/test_qa_agent_actions.py:46:49: F811 redefinition of unused 'get_llm' from line 8
tests/integration_tests/test_qa_agent_actions.py:72:55: F811 redefinition of unused 'get_llm' from line 8